services:
  - type: static
    name: eblogging-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: eblogging-backend
          property: host

  - type: web
    name: eblogging-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://ssjsamar453_db_user:<#Gokussj4>@cluster0.mbnnf3i.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
